### ISSUE TITLE
Integrate wireless functionality to the Nicla board

### ISSUE THREAD

**Issue by jack-margeson** [EECE3093C/team-project-green-arduino#4]
This ticket includes:
- Finding a breadboard for testing connections between the Nicla ME and the chosen wireless module (see the [hardware documentation](https://github.com/EECE3093C/team-project-green/blob/main/hardware_documentation.md))
- Connecting the Nicla ME to the wireless module 
- Sending test data to and from a host system 
- Sending test data to and from a new Firebase testing database

This ticket does not include:
- Setting up formal data structures for the data we're sending to the production Firebase database 
- Integrating with the team's Firebase being set up in https://github.com/EECE3093C/team-project-green-software/issues/7

**Comment by MJ-Schnee** [comment]
I think that's a really good idea. What matters is getting something working and it seems like what you've proposed here will do that (and it seems like you have a really solid plan worked out already)! Less hardware demands and faster development is always a plus, especially since cost isn't an issue

**Comment by jack-margeson** [comment]
https://github.com/EECE3093C/team-project-green/issues/29 updates the hardware documentation in the main repository, like we had talked about doing during today's team meeting. I am going to close this ticket as we no longer require wireless functionality directly on the Nicla board.
